# # -()- Quick test runs
#use_location_ids: ["AC", "SP"]
#use_projection_years: [2022, 2023]
#ncpus: 1
#output_dir: "outputs/quick_test_runs"

# -()- Full runs
use_location_ids: []
use_projection_years: [2022, 2023, 2024, 2025]
ncpus: 6

## -()- Sensitivity: No update from outbreak features
#use_location_ids: []
#use_projection_years: [2022, 2023, 2024, 2025]
#ncpus: 6
#output_dir: "outputs/sensitivity/no_update_from_outbreak_features"
